# Generated by Django 2.2.24 on 2021-11-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification_notify', '0002_notificationprofile_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationprofile',
            old_name='state',
            new_name='read',
        ),
    ]
